apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.converter.name }}-clusterip
spec:
  selector:
    components: {{ .Values.converter.components }}
  ports:
    - protocol: TCP
      port: {{ .Values.converter.port }}
  type: ClusterIP
