apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.name }}-secret
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
  SEED_USERNAME: "guest"
  SEED_PASSWORD: "guest"
  AMQP_EXCHANGE: "conv-exchange"
  AMQP_HOSTNAME: "rabbitmq-clusterip"
  AMQP_USER: "guest"
  AMQP_PASSWORD: "guest"
  AMQP_QUEUE: "conv-queue"
