apiVersion: v1
kind: Secret
metadata:
  name: conv-api-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
  SEED_USERNAME: Z3Vlc3Q=
  SEED_PASSWORD: Z3Vlc3Q=
  AMPQ_EXCHANGE: Y29udi1leGNoYW5nZQ==
  AMPQ_HOSTNAME: Z3Vlc3Q=
  AMPQ_USER: Z3Vlc3Q=
  AMPQ_PASSWORD: Z3Vlc3Q=

  
