apiVersion: v1
kind: Secret
metadata:
  name: conv-api-secret
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "demo"
  RABBITMQ_DEFAULT_PASS: "demo"
  SEED_USERNAME: "demo"
  SEED_PASSWORD: "demo"
  AMQP_EXCHANGE: "conv-exchange"
  AMQP_HOSTNAME: "demo"
  AMQP_USER: "demo"
  AMQP_PASSWORD: "demo"
  AMQP_QUEUE: "conv-queue"
